version: 2.1

orbs:
  codacy: codacy/base@12.1.1

workflows:
  version: 2

  compile_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt_docker:
          name: test
          steps:
            - run:
                name: Compile tests
                command: sbt +test:compile
          setup_remote_docker: false
          context: CodacyAWS
          requires:
            - codacy/checkout_and_version
      - codacy/sbt_docker:
          name: publish
          steps:
            - run:
                name: Retrieve GPG keys
                command: sbt retrieveGPGKeys
            - run:
                name: Publish to bundle
                command: sbt +publishSigned
            - run:
                name: Release bundle to Sonatype
                command: sbt sonatypeBundleRelease
          setup_remote_docker: false
          context: CodacyAWS
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          context: CodacyAWS
          requires:
            - publish
